"""ALSA configuration helpers for click playback."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

MASTER_CLOCK_PCM_NAME = "master_clock"
SYSTEM_ALSA_CONFIG = "/usr/share/alsa/alsa.conf"

CARD_DEVICE_PATTERN = re.compile(
    r"^(?P<prefix>plug)?hw:CARD=(?P<card>[^,]+),DEV=(?P<device>\d+)$",
    re.IGNORECASE,
)
NUMERIC_ALSA_DEVICE_PATTERN = re.compile(
    r"^(?P<prefix>plug)?hw:(?P<card>\d+),(?P<device>\d+)$",
    re.IGNORECASE,
)


def alsa_stable_device_id(
    card_name: str,
    device_index: int | str,
    *,
    plug: bool = True,
) -> str:
    """Return a stable ALSA device id based on card name instead of card number."""

    prefix = "plughw" if plug else "hw"
    card = card_name.strip()
    return f"{prefix}:CARD={card},DEV={int(device_index)}"


def lookup_alsa_output_device(
    device: str,
    devices: list[dict[str, Any]] | None = None,
) -> dict[str, Any] | None:
    from midijuggler.system_info import list_alsa_output_devices

    listed = list_alsa_output_devices() if devices is None else devices
    normalized = device.strip()
    if not normalized:
        return next((entry for entry in listed if not entry.get("id")), None)

    for entry in listed:
        if entry.get("id") == normalized:
            return entry

    card_match = CARD_DEVICE_PATTERN.match(normalized)
    if card_match is not None:
        card_name = card_match.group("card")
        device_index = card_match.group("device")
        for entry in listed:
            if (
                entry.get("card_name") == card_name
                and str(entry.get("device_index")) == device_index
            ):
                return entry

    numeric_match = NUMERIC_ALSA_DEVICE_PATTERN.match(normalized)
    if numeric_match is not None:
        card_number = numeric_match.group("card")
        device_index = numeric_match.group("device")
        for entry in listed:
            if (
                str(entry.get("card_number")) == card_number
                and str(entry.get("device_index")) == device_index
            ):
                return entry

    return None


def normalize_alsa_output_device(
    device: str,
    devices: list[dict[str, Any]] | None = None,
) -> str:
    """Prefer stable CARD= device ids and migrate legacy plughw:N,M values."""

    normalized = device.strip()
    if not normalized:
        return ""

    if CARD_DEVICE_PATTERN.match(normalized):
        return normalized

    matched = lookup_alsa_output_device(normalized, devices=devices)
    if matched is not None and matched.get("id"):
        return str(matched["id"])

    return normalized


def resolve_alsa_output_device(
    device: str,
    devices: list[dict[str, Any]] | None = None,
) -> str:
    """Return the configured ALSA device string for playback."""

    return normalize_alsa_output_device(device, devices=devices)


def alsa_config_path_for_config(config_path: str | Path | None) -> Path | None:
    if config_path is None:
        return None
    return Path(config_path).with_name("asoundrc")


def render_master_clock_pcm(
    slave_pcm: str,
    mode: str | None = None,
    pcm_name: str = MASTER_CLOCK_PCM_NAME,
) -> str:
    """Render an ALSA config defining the master-clock PCM."""

    slave_pcm = slave_pcm or "default"
    mode = mode or alsa_mode_for_device(slave_pcm)
    if mode == "alias":
        body = _render_alias_pcm(slave_pcm, pcm_name)
    elif mode == "dmix":
        body = _render_dmix_pcm(slave_pcm, pcm_name)
    else:
        raise ValueError("ALSA master_clock mode must be 'dmix' or 'alias'")

    return (
        "# Generated by MIDIJuggler. Do not edit while the service is running.\n"
        f"<{SYSTEM_ALSA_CONFIG}>\n\n"
        + body
    )


def render_master_clock_dmix(
    slave_pcm: str,
    pcm_name: str = MASTER_CLOCK_PCM_NAME,
) -> str:
    """Render a named dmix PCM for backwards-compatible callers."""

    return render_master_clock_pcm(slave_pcm, mode="dmix", pcm_name=pcm_name)


def alsa_mode_for_device(device: str) -> str:
    """Choose dmix for hardware PCMs and alias for software PCMs."""

    return "dmix" if _is_hardware_pcm(device) else "alias"


def write_master_clock_pcm_config(path: str | Path, slave_pcm: str) -> None:
    config_path = Path(path)
    temp_path = config_path.with_suffix(config_path.suffix + ".tmp")
    temp_path.write_text(render_master_clock_pcm(slave_pcm), encoding="utf-8")
    temp_path.replace(config_path)


def write_master_clock_dmix_config(path: str | Path, slave_pcm: str) -> None:
    """Backward-compatible alias for writing the master-clock PCM config."""

    write_master_clock_pcm_config(path, slave_pcm)


def _render_dmix_pcm(slave_pcm: str, pcm_name: str) -> str:
    slave_pcm = _dmix_slave_pcm(slave_pcm)
    dmix_pcm_name = f"{pcm_name}_dmix"
    return (
        f"pcm.{pcm_name} {{\n"
        "    type plug\n"
        f"    slave.pcm {_alsa_string(dmix_pcm_name)}\n"
        "}\n\n"
        f"pcm.{dmix_pcm_name} {{\n"
        "    type dmix\n"
        "    ipc_key 426110\n"
        "    ipc_perm 0666\n"
        "    slave {\n"
        f"        pcm {_alsa_string(slave_pcm)}\n"
        "        rate 44100\n"
        "        channels 2\n"
        "        period_size 1024\n"
        "        buffer_size 4096\n"
        "    }\n"
        "}\n\n"
    )


def _render_alias_pcm(slave_pcm: str, pcm_name: str) -> str:
    return (
        f"pcm.{pcm_name} {{\n"
        "    type plug\n"
        f"    slave.pcm {_alsa_string(slave_pcm)}\n"
        "}\n\n"
    )


def _is_hardware_pcm(device: str) -> bool:
    if CARD_DEVICE_PATTERN.match(device):
        return True
    return device.startswith("hw:") or device.startswith("plughw:")


def _dmix_slave_pcm(device: str) -> str:
    """Return a dmix-compatible slave PCM.

    ALSA dmix can only connect directly to the hw plugin. User-facing device
    lists often prefer plughw for format conversion, but plughw cannot be the
    dmix slave.
    """

    if device.startswith("plughw:"):
        return "hw:" + device.removeprefix("plughw:")
    return device


def _alsa_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
