"""ALSA configuration helpers for click playback."""

from __future__ import annotations

from pathlib import Path

MASTER_CLOCK_PCM_NAME = "master_clock"
SYSTEM_ALSA_CONFIG = "/usr/share/alsa/alsa.conf"


def alsa_config_path_for_config(config_path: str | Path | None) -> Path | None:
    if config_path is None:
        return None
    return Path(config_path).with_name("asoundrc")


def render_master_clock_dmix(
    slave_pcm: str,
    pcm_name: str = MASTER_CLOCK_PCM_NAME,
) -> str:
    """Render an ALSA config defining a named dmix PCM."""

    slave_pcm = slave_pcm or "default"
    return (
        "# Generated by MIDIJuggler. Do not edit while the service is running.\n"
        f"<{SYSTEM_ALSA_CONFIG}>\n\n"
        f"pcm.{pcm_name} {{\n"
        "    type dmix\n"
        "    ipc_key 426110\n"
        "    ipc_perm 0666\n"
        "    slave {\n"
        f"        pcm {_alsa_string(slave_pcm)}\n"
        "        rate 44100\n"
        "        channels 2\n"
        "        period_size 1024\n"
        "        buffer_size 4096\n"
        "    }\n"
        "}\n\n"
    )


def write_master_clock_dmix_config(path: str | Path, slave_pcm: str) -> None:
    config_path = Path(path)
    temp_path = config_path.with_suffix(config_path.suffix + ".tmp")
    temp_path.write_text(render_master_clock_dmix(slave_pcm), encoding="utf-8")
    temp_path.replace(config_path)


def _alsa_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
