"""ALSA configuration helpers for click playback."""

from __future__ import annotations

from pathlib import Path

MASTER_CLOCK_PCM_NAME = "master_clock"
SYSTEM_ALSA_CONFIG = "/usr/share/alsa/alsa.conf"


def alsa_config_path_for_config(config_path: str | Path | None) -> Path | None:
    if config_path is None:
        return None
    return Path(config_path).with_name("asoundrc")


def render_master_clock_pcm(
    slave_pcm: str,
    mode: str | None = None,
    pcm_name: str = MASTER_CLOCK_PCM_NAME,
) -> str:
    """Render an ALSA config defining the master-clock PCM."""

    slave_pcm = slave_pcm or "default"
    mode = mode or alsa_mode_for_device(slave_pcm)
    if mode == "alias":
        body = _render_alias_pcm(slave_pcm, pcm_name)
    elif mode == "dmix":
        body = _render_dmix_pcm(slave_pcm, pcm_name)
    else:
        raise ValueError("ALSA master_clock mode must be 'dmix' or 'alias'")

    return (
        "# Generated by MIDIJuggler. Do not edit while the service is running.\n"
        f"<{SYSTEM_ALSA_CONFIG}>\n\n"
        + body
    )


def render_master_clock_dmix(
    slave_pcm: str,
    pcm_name: str = MASTER_CLOCK_PCM_NAME,
) -> str:
    """Render a named dmix PCM for backwards-compatible callers."""

    return render_master_clock_pcm(slave_pcm, mode="dmix", pcm_name=pcm_name)


def alsa_mode_for_device(device: str) -> str:
    """Choose dmix for hardware PCMs and alias for software PCMs."""

    return "dmix" if _is_hardware_pcm(device) else "alias"


def write_master_clock_pcm_config(path: str | Path, slave_pcm: str) -> None:
    config_path = Path(path)
    temp_path = config_path.with_suffix(config_path.suffix + ".tmp")
    temp_path.write_text(render_master_clock_pcm(slave_pcm), encoding="utf-8")
    temp_path.replace(config_path)


def write_master_clock_dmix_config(path: str | Path, slave_pcm: str) -> None:
    """Backward-compatible alias for writing the master-clock PCM config."""

    write_master_clock_pcm_config(path, slave_pcm)


def _render_dmix_pcm(slave_pcm: str, pcm_name: str) -> str:
    return (
        f"pcm.{pcm_name} {{\n"
        "    type dmix\n"
        "    ipc_key 426110\n"
        "    ipc_perm 0666\n"
        "    slave {\n"
        f"        pcm {_alsa_string(slave_pcm)}\n"
        "        rate 44100\n"
        "        channels 2\n"
        "        period_size 1024\n"
        "        buffer_size 4096\n"
        "    }\n"
        "}\n\n"
    )


def _render_alias_pcm(slave_pcm: str, pcm_name: str) -> str:
    return (
        f"pcm.{pcm_name} {{\n"
        "    type plug\n"
        f"    slave.pcm {_alsa_string(slave_pcm)}\n"
        "}\n\n"
    )


def _is_hardware_pcm(device: str) -> bool:
    return device.startswith("hw:") or device.startswith("plughw:")


def _alsa_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
