Section "ServerFlags"
    Option "DontVTSwitch" "true"
EndSection

Section "Device"
    Identifier  "FBDEV"
    Driver      "fbdev"
    Option      "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier  "Screen0"
    Device      "FBDEV"
EndSection

Section "ServerLayout"
    Identifier  "Layout0"
    Screen      "Screen0"
EndSection
